# This file was generated by CMake for @PROJECT_NAME@ library @PKG_NAME@
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include/Myro-Cpp

Name: @PROJECT_NAME@
Description: @PKG_DESC@
Version: @PKG_VERSION@
Requires: @PKG_EXTERNAL_DEPS@
Libs: -L${libdir} -lmyro-cpp
Cflags: -I${includedir}
